name: Terraform infra pipeline

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.tf"
      - "tf/**"
  push:
    branches: [main]
    paths:
      - "**/*.tf"
      - "tf/**"

permissions:
  contents: read
  pull-requests: write
  actions: write
  id-token: write
jobs:
  #############################################################
  # 1. Terraform FMT Job
  #############################################################
  terraform_fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform fmt check
        run: terraform fmt -recursive -check



  #############################################################
  # 2. Terraform INIT Job
  #############################################################
  terraform_init:
    runs-on: ubuntu-latest
    needs: terraform_fmt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform init
        run: terraform init \
          -backend-config="bucket=${{ secrets.AWS_ROLE_ARN }}" \
          -backend-config="key=uat/terraform.tfstate"



  #############################################################
  # 3. Terraform VALIDATE Job
  #############################################################
  terraform_validate:
    runs-on: ubuntu-latest
    needs: terraform_init

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform validate
        run: terraform validate

      - name: Run TFLint
        run: tflint --init && tflint

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif



  #############################################################
  # 4. Terraform PLAN Job
  #############################################################
  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform init
        run: terraform init \
          -backend-config="bucket=${{ secrets.AWS_ROLE_ARN }}" \
          -backend-config="key=uat/terraform.tfstate"

      - name: Terraform plan
        run: terraform plan -out=plan.out

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: plan.out
          retention-days: 1



  #############################################################
  # 5. Terraform APPLY Job (only on push to main)
  #############################################################
  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform init
        run: terraform init \
          -backend-config="bucket=${{ secrets.AWS_ROLE_ARN }}" \
          -backend-config="key=uat/terraform.tfstate"

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-plan
          path: .

      - name: Terraform apply
        run: terraform apply -auto-approve plan.out





